const screen = {
  Home: "Explore",
  Location: "Location",
  CropSelection: "CropSelection",
  Explore: "Explore ",
  Activity: "Activity",
  ActivityDetails: "ActivityDetails",
  EditProfile: "EditProfile",
  Settings: "Settings",
  ProductDetails: "ProductDetails",
  ArticleDetails: "ArticleDetails",
  Weather: "Weather",
  About: "About",
  Help: "Help",
  Logout: "Logout",
};
